export * from './auth';
export * from './home';
export * from './otp';
export * from './dashboard';
export * from './builder';
export * from './play';
export * from './tutor';
export * from './profile';
export * from './nav';
