export const TUTOR = {
        topicInput: 'tutor-topic-input',
        levelSelect: 'tutor-level-select',
        startButton: 'tutor-start-button',
        questionText: 'tutor-question-text',
        optionButton: 'tutor-option-button',
        submitAnswerButton: 'tutor-submit-answer-button',
        difficultyPill: 'tutor-difficulty-pill',
        conceptPill: 'tutor-concept-pill',
        feedbackCorrect: 'tutor-feedback-correct',
        feedbackWrong: 'tutor-feedback-wrong',
        feedbackExplanation: 'tutor-feedback-explanation',
        masteryRow: 'tutor-mastery-row',
        endSessionButton: 'tutor-end-session-button',
        askFromDocButton: 'tutor-ask-from-doc-button',
        nextButton: 'tutor-next-button',
        ragToggle: 'tutor-rag-toggle',
        uploadInput: 'tutor-upload-input',
        uploadButton: 'tutor-upload-button',
        documentRow: 'tutor-document-row',
        summaryPanel: 'tutor-summary-panel',
        errorAlert: 'tutor-error-alert',
};
